# Generated by Django 6.0.2 on 2026-02-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlogs',
            name='plate_number',
            field=models.CharField(verbose_name='plate number'),
        ),
    ]
