# Generated by Django 6.0.2 on 2026-02-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameras',
            options={'verbose_name': 'Cameras', 'verbose_name_plural': 'Cameras'},
        ),
    ]
