services:
  redis:
    image: redis
    container_name: traffic-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
  db:
    image: postgres:latest
    container_name: traffic-postgres
    restart: always
    volumes:
      - traffic-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=traffic
      - POSTGRES_NAME=traffic
      - POSTGRES_USER=traffic@user
      - POSTGRES_PASSWORD=traffic@2684
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    expose:
      - "5432"

  neo4j: 
    image: neo4j:5
    container_name : traffic-neo4j
    restart : always
    environment:
      - NEO4J_AUTH=neo4j/traffic@2684
    ports:
    - "7687:7687"
    - "7474:7474"

    volumes:
    - traffic-neo4j:/data
    
  backend:
    image: traffic
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: traffic-backend
    environment:
      # Django Envs
      - DEBUG=True
      - SECRET_KEY=Fahim12345678@86;

      # Postgres Envs
      - DB_NAME=traffic
      - DB_USER=traffic@user
      - DB_PASSWORD=traffic@2684
      - DB_HOST=db
      - DB_PORT=5432
      
      # Neo4j Envs
      - NEO4J_AUTH=neo4j/trafficlogs@2684
    ports:
    - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/usr/src/app
    depends_on:
      - db
      - redis
      - neo4j
  
  celery:
    container_name: traffic-celery
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes: 
      - ./core:/usr/src/app
    environment:
      # Django Envs

      - DEBUG=True
      - SECRET_KEY=Fahim12345678@86;

      # Neo4j Envs
      - NEO4J_AUTH=neo4j/trafficlogs@2684
    command: celery -A core worker --loglevel=info -Q celery,celery:1,celery:2
    depends_on:
      - db
      - redis
      - backend
  
  celery_beat:
    container_name: traffic-celery_beat
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes: 
      - ./core:/usr/src/app
    environment:
      # Django Envs

      - DEBUG=True
      - SECRET_KEY=Fahim12345678@86;
      
      # Neo4j Envs
      - NEO4J_AUTH=neo4j/trafficlogs@2684
    depends_on:
      - db
      - redis
      - backend
      - celery
  

volumes:
  traffic-postgres:
  traffic-neo4j: